De-debianize dotfiles script

diff --git a/.local/bin/dotfiles b/.local/bin/dotfiles
--- a/.local/bin/dotfiles
+++ b/.local/bin/dotfiles
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
 set -e
 
@@ -12,9 +12,6 @@ declare -a files=(
     .Xresources
     .bin
     .cig
-    .emacs.d
-    .gitconfig
-    .gitignore_global
     .gtkrc-2.0
     .keynavrc
     .mbsyncrc
@@ -30,10 +27,17 @@ declare -a files=(
 
 declare -a cherrypick=(
     .gnupg
+    .local/bin
     .local/lib
     .local/share/applications
     .config
 )
+
+log_error() {
+    tput setab 1
+    tput setaf 3
+    echo "ERROR"
+}
 
 mksymlink() {
     # Symlinks $1 to $2
@@ -42,36 +46,44 @@ mksymlink() {
     dest=$2
 
     if [ -e "$src.$(hostname)" ]; then
+        local basename=$src
         src="$src.$(hostname)"
-        echo "Notice: Will use $src for $dest"
+        echo -e "\t(variant) $src -> $dest"
     fi
 
     if [ ! -e $src ]; then
-        echo "Warning: No source file '$src'."
+        echo -e "\tMISSING No source file '$src'."
         return
     fi
 
     if [ -e "$dest" ]; then
         if [ $(realpath "$src") == $(realpath "$dest") ]; then
             let notrelinked+=1
-            return 0
+            return
         else
-            echo -e "WARNING\t A different $dest already exists.  NOT LINKING."
-            return 1
+            log_error "A different $dest already exists.  NOT LINKING."
+            let errors+=1
+            return
         fi
     fi
 
     ln -s "$src" "$dest"
     let count+=1
 }
-notrelinked=0
+
 count=0
+notrelinked=0
+errors=0
+
+echo "[Regular files]"
 
 for t in "${files[@]}"; do
     mksymlink "$DOTFILES/$t" "$HOME/$t"
 done
 
-# Cherrypicking
+# Cherrypicking
+
+echo "[Cherry-picked paths]"
 
 for d in "${cherrypick[@]}"; do
     mkdir -p $HOME/$d
@@ -79,6 +91,8 @@ for d in "${cherrypick[@]}"; do
         mksymlink "$DOTFILES/$d/$t" "$HOME/$d/$t"
     done
 done
+
+echo "[$PRIVFILES]"
 
 # Private files.  A simple mirroring.
 cd $PRIVFILES
@@ -88,4 +102,6 @@ for t in $files; do
 done
 
 echo
-echo "$count files linked, $notrelinked were already present."
+echo "$count files linked, $errors errors, $notrelinked existing symlinks not modified."
+
+exit $errors
